AUDIT_CSV_HEADERS = [
    "Date of Audit",
    "Transaction Date",
    "Transaction ID",
    "Transaction Type",
    "Agent name",
    "Team Leader",
    "LOB",
    "Observer's Name",
    "Audit ID",
    "Apptivo",
    "Oppurtunities",
    "Logical Itinerary (Time window, Routing, Connections)",
    "Applied Commission as applicable (Retained / Parted)",
    "Frequent Flyer - Air & Loyalty Membership - Car, Hotels",
    "Offered Limo where applicable and Ensuring complete address & phone number",
    "Preferences – Seat, Meal",
    "Transit Visa advisory",
    "PNR Documentation in P5H & Reference (Receive Field)",
    "Captured correct Apptivo case number & used Apptivo for communication",
    "Options & class of service as per client policy",
    "No Show / Cancellations / Changes to be advised correctly",
    "Capture accurate reason codes (Missed/Realized) & Low Fare in the script",
    "Corporate deal application for Air/Car/Hotel",
    "Process accurate re-issuance (Tax code, add collect, WFRF, WFR)",
    "Correct form of payment",
    "Client Specifics (if any) & Standard Operating Procedure related",
    "DIN entry as applicable",
    "Process accurate accounting line - PAC",
    "Correct POS indicator & POS fee",
    "Correct Service fee selection (Air, Car, Hotel, Other)",
    "Overall communication in the email",
    "Used CWT Itinerary / Clipboard / Sabre format as per client",
    "Utilized cross sell & up sell opportunity (Hotel, Car, Insurance)",
    "Quotation based on request (Date, Time, City Pair)",
    "Max Score",
    "Quality Score",
    "Score without Fatal",
    "FATAL Transaction",
    "PNR Fields",
    "Client Policy and Service",
    "Accounting",
    "Communication",
    "FEEDBACK"
]

# Verification: Print the number of headers
# This part is for my own verification and won't be in the file.
# print(f"Number of headers: {len(AUDIT_CSV_HEADERS)}")
